# Generated by Django 4.2.3 on 2023-07-30 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('habilidades', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('requisitos_excluyentes', models.TextField()),
                ('requisitos_no_excluyentes', models.TextField()),
                ('salario_ofrecido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(max_length=50)),
                ('salario_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('job_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.solicitante')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.trabajo')),
            ],
        ),
    ]
